pipeline {
  agent any
  environment {
    gitCredentialsId = 'github-jenkins-ssh'
    artifactTergetDir = 'oc-build'
    buildArtifactSmeApp = 'dist/apps/sme-app'
    buildConfigNameSmeApp = 'sme-app-image'
//    OpenShiftProjectDev = 'axa-advice-sme-dev-axa-ch'
//    OpenShiftClusterName = 'axa-advice-sme-dev-axa-ch-private-blue'
  }
  stages {
    stage('first-step'){
      steps{
        sh 'echo "Helloooooo!!!"'
      }
    }
    stage('Set variables') {
      steps {
        script {
          gitBranch = GIT_BRANCH
          sh 'git config --global user.email "srdjan@3ap.ch"'
          sh 'git config --global user.name "Srdjan Obradovic"'
          // fix "detached HEAD" state
          sh "git checkout ${gitBranch}"
        }
      }
    }
  }
}
